### ISSUE TITLE
Degree-dropdown in settings should get data from enum

### ISSUE THREAD

**Issue by bjornarjatten** [simoboye/BDSA2020#37]

**Comment by bjornarjatten** [comment]
![image](https://user-images.githubusercontent.com/20386318/101296025-6be24800-3821-11eb-8b5d-4ed49ea30d34.png)
Cannot seem to get it to iterate over the enum, created this soultion instead.

**Comment by simoboye** [comment]
Have you tried using this: `Enum.GetValues(typeof(Degree)`?
